commerce_payment.commerce_payment_gateway.plugin.mobilpay_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_signature:
      type: string
      label: 'Merchant signature'
    test_mobilpay_checkout_private_key:
      type: string
      label: 'Test Private key'
    test_mobilpay_checkout_public_key:
      type: string
      label: 'Test Public key'
    live_mobilpay_checkout_private_key:
      type: string
      label: 'Test Private key'
    live_mobilpay_checkout_public_key:
      type: string
      label: 'Test Public key'
